### ISSUE TITLE
🐛 [Bug] [Federation] Error: Too few nodes responded

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#2406]
## 🐛 Bugreport

We get the following error on our systems with DHT enabled:

```
Error: Too few nodes responded
2022-11-21 10:30:45.043:     at Query._endAfterCommit (/home/gradido/gradido/backend/node_modules/dht-rpc/lib/query.js:196:20)
2022-11-21 10:30:45.043:     at Query._flush (/home/gradido/gradido/backend/node_modules/dht-rpc/lib/query.js:191:10)
2022-11-21 10:30:45.043:     at Query._readMore (/home/gradido/gradido/backend/node_modules/dht-rpc/lib/query.js:176:12)
2022-11-21 10:30:45.043:     at Query._read (/home/gradido/gradido/backend/node_modules/dht-rpc/lib/query.js:144:10)
2022-11-21 10:30:45.043:     at ReadableState.update (/home/gradido/gradido/backend/node_modules/streamx/index.js:324:14)
2022-11-21 10:30:45.043:     at ReadableState.afterOpen (/home/gradido/gradido/backend/node_modules/streamx/index.js:505:27)
2022-11-21 10:30:45.043:     at /home/gradido/gradido/backend/node_modules/dht-rpc/lib/query.js:106:7
2022-11-21 10:30:45.043:     at GetAddrInfoReqWrap.callback (/home/gradido/gradido/backend/node_modules/dht-rpc/index.js:583:30)
2022-11-21 10:30:45.043:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:17)
2022-11-21 10:30:45.095: error Command failed with exit code 1.
```

Presumably this crashes our service and pm2 then restarts it.

Make sure:
- that our service doesn't crash
- that the DHT search is restarted, even when initially not enough nodes were found

Repro:
1. Start Service on a new topic
2. Get error
3. Start a second service on the same topic
4. Service1 should be found and find Service2

**Comment by clauspeterhuebner** [comment]
I could reproduce this error on my local machine.
Please see the log-output in the attached file:
[DHT_TooFewNodesResponded_Error.txt](https://github.com/gradido/gradido/files/10319614/DHT_TooFewNodesResponded_Error.txt)

the dht-lib invokes "this.destroy()" if no other node could be detected. 
So the open question is how to catch or react on such a destroy-invocation to avoid a complet end-of-execution of the node-process?
